language: ruby
cache: bundler
sudo: false

rvm:
        #  - 2.0
        #  - 2.1
        #  - 2.2
  - 2.2.3

bundler_args: --without development kitchen_docker kitchen_vagrant

script:
  - bundle exec foodcritic -f any .
  # - bundle exec rspec --color --format progress
  - bundle exec rubocop

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/dc143a4bf4fb95b75249
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
